### ISSUE TITLE
Unable to compile on MacOS 10.15 (Catalina) with VTK 9 and Cmake 3.18

### ISSUE THREAD

**Issue by omhafez** [valette/ACVD#35]
Hello, I've come across a slew of compilation errors using the environment described above. Do you guys plan to support these? Example error below.

Thanks,
Omar

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: 
      no member named 'signbit' in the global namespace
using ::signbit;`

**Comment by valette** [comment]
Hi, I have created a branch for vtk9 : [/valette/ACVD/tree/vtk9](/valette/ACVD/tree/vtk9) 
Could you test it?

**Comment by valette** [comment]
Should work now, pleas re-open the bug if not!
